version: '3.8'

services:
  fastapi_chatbot:
    restart: always
    build: .
    ports:
      - "3080:3080"
    env_file:
      - .env
    command: sh -c 'uvicorn main:app --host 0.0.0.0 --port 3080'
